const API_BASE_URL = "http://192.168.102.82:8080/api";
// const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL;
const GOOGLE_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_CLIENT_ID!;
const PLATFORM = "greenvision.dev.com";
const APPWRITE_ENDPOINT = process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!;
const APPWRITE_PROJECT_ID = process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!;

export default {
  API_BASE_URL,
  GOOGLE_CLIENT_ID,
  PLATFORM,
  APPWRITE_ENDPOINT,
  APPWRITE_PROJECT_ID,
};
